import { faker } from '@faker-js/faker';

export const transactions = [
  {
    token: 'stETH',
    type: 'approval',
    status: 'success',
    url: faker.internet.url(),
    tokenIcon: 'https://oeth.on.fleek.co/images/currency/steth-icon-small.svg',
  },
  {
    token: 'stETH',
    type: 'approval',
    status: 'pending',
    url: faker.internet.url(),
    tokenIcon: 'https://oeth.on.fleek.co/images/currency/steth-icon-small.svg',
  },
  {
    token: 'stETH',
    type: 'approval',
    status: 'failed',
    url: faker.internet.url(),
    tokenIcon: 'https://oeth.on.fleek.co/images/currency/steth-icon-small.svg',
  },
  {
    token: 'OETH',
    type: 'rebase',
    status: 'success',
    url: faker.internet.url(),
    tokenIcon: 'https://app.oeth.com/images/oeth.svg',
  },
  {
    token: 'OETH',
    type: 'rebase',
    status: 'pending',
    url: faker.internet.url(),
    tokenIcon: 'https://app.oeth.com/images/oeth.svg',
  },
  {
    token: 'OETH',
    type: 'rebase',
    status: 'failed',
    url: faker.internet.url(),
    tokenIcon: 'https://app.oeth.com/images/oeth.svg',
  },
  {
    baseToken: 'stETH',
    baseTokenQuantity: 4.7713,
    type: 'swap',
    status: 'success',
    url: faker.internet.url(),
    exchangeToken: 'OETH',
    exchangeTokenQuantity: 4.815,
    exchangeTokenIcon: 'https://app.oeth.com/images/oeth.svg',
    baseTokenIcon: 'https://app.oeth.com/images/currency/steth-icon-small.svg',
  },
  {
    baseToken: 'stETH',
    baseTokenQuantity: 4.7713,
    type: 'swap',
    status: 'failed',
    url: faker.internet.url(),
    exchangeToken: 'OETH',
    exchangeTokenQuantity: 4.815,
    exchangeTokenIcon: 'https://app.oeth.com/images/oeth.svg',
    baseTokenIcon: 'https://app.oeth.com/images/currency/steth-icon-small.svg',
  },
  {
    baseToken: 'stETH',
    baseTokenQuantity: 4.7713,
    type: 'swap',
    status: 'pending',
    url: faker.internet.url(),
    exchangeToken: 'OETH',
    exchangeTokenQuantity: 4.815,
    exchangeTokenIcon: 'https://app.oeth.com/images/oeth.svg',
    baseTokenIcon: 'https://app.oeth.com/images/currency/steth-icon-small.svg',
  },
  {
    exchangeToken: 'stETH',
    exchangeTokenQuantity: 4.7713,
    type: 'redeem',
    status: 'pending',
    url: faker.internet.url(),
    baseToken: 'OETH',
    baseTokenQuantity: 4.815,
    baseTokenIcon: 'https://app.oeth.com/images/oeth.svg',
    exchangeTokenIcon:
      'https://app.oeth.com/images/currency/steth-icon-small.svg',
  },
  {
    exchangeToken: 'stETH',
    exchangeTokenQuantity: 4.7713,
    type: 'redeem',
    status: 'success',
    url: faker.internet.url(),
    baseToken: 'OETH',
    baseTokenQuantity: 4.815,
    baseTokenIcon: 'https://app.oeth.com/images/oeth.svg',
    exchangeTokenIcon:
      'https://app.oeth.com/images/currency/steth-icon-small.svg',
  },
  {
    exchangeToken: 'stETH',
    exchangeTokenQuantity: 4.7713,
    type: 'redeem',
    status: 'failed',
    url: faker.internet.url(),
    baseToken: 'OETH',
    baseTokenQuantity: 4.815,
    baseTokenIcon: 'https://app.oeth.com/images/oeth.svg',
    exchangeTokenIcon:
      'https://app.oeth.com/images/currency/steth-icon-small.svg',
  },
];
