name: defi main

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Fleek CLI
        run: pnpm add -g @fleek-platform/cli

      - name: Build
        env:
          alchemy_id: ${{ secrets.VITE_ALCHEMY_ID_DEFI }}
          gtm_container: ${{ secrets.VITE_GTM_CONTAINER_ID_DEFI }}
          sentry_dns: ${{ secrets.VITE_SENTRY_DSN_DEFI }}
          wc_project_id: ${{ secrets.VITE_WALLET_CONNECT_PROJECT_ID_DEFI }}
        run: |
          VITE_WALLET_CONNECT_PROJECT_ID=$wc_project_id \
          VITE_ALCHEMY_ID=$alchemy_id \
          VITE_GTM_CONTAINER_ID=$gtm_container \
          VITE_SENTRY_DSN=$wc_project_id \
          pnpm nx run build defi

      - name: Upload to IPFS
        run: fleek storage add ./dist/apps/defi
